#!/usr/bin/awk -f

BEGIN {
  w = (width ? 16 * width : 8192)

  for (i = 2; i <= w; i++) {
    if (c[i]) {
      continue
    }

    p[n++] = i
    if (i * i <= w) {
      for (j = i * i; j <= w; j += i) {
        c[j] = 1
      }
    }
  }

  printf "// Auto-generated by src/gen-primes.awk\n"
  printf "#ifndef PRIMES_H\n"
  printf "#define PRIMES_H\n\n"
  printf "#include <stdint.h>\n\n"
  printf "#define N_PRIMES %d\n\n", n
  printf "static const uint64_t PRIMES[N_PRIMES] = {"

  for (i = 0; i < n; i++) {
    if (i % 13 == 0) {
      printf "\n  "
    }

    printf "%4d, ", p[i]
  }

  printf "\n};\n\n"
  printf "#endif // PRIMES_H\n"
}
